name: Run tests

on: push

env: 
  MONGO_VERSION: 4.4.2

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15

    - name: Vet code
      run: go vet ./...

    - name: Lint code
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.34

    - name: Download MongoDB and setup standalone db
      run: |
        wget http://downloads.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-$MONGO_VERSION.tgz
        tar xzvf mongodb-linux-x86_64-ubuntu1804-$MONGO_VERSION.tgz
        echo "$PWD/mongodb-linux-x86_64-ubuntu1804-$MONGO_VERSION/bin" >> $GITHUB_PATH
        mkdir $PWD/db
        mongod --dbpath $PWD/db --logpath /dev/null --nojournal --fork

    - name: Run test
      run: scripts/test.sh
    
    - name: Export coverage result 
      run: bash <(curl -s https://codecov.io/bash)
