name: Run tests

on: [push]

env: 
  MONGO_VERSION: 4.2.3

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: Vet and lint code
      run: |
        go get -u -v golang.org/x/lint/golint 
        /home/runner/go/bin/golint ./... 
        go vet ./...

    - name: Download MongoDB
      run: |
        wget http://downloads.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-$MONGO_VERSION.tgz
        tar xzvf mongodb-linux-x86_64-ubuntu1804-$MONGO_VERSION.tgz
        mkdir $PWD/db

    - name: Start mongod server and run test
      run: |
        export PATH=$PWD/mongodb-linux-x86_64-ubuntu1804-$MONGO_VERSION/bin:$PATH
        mongod --dbpath $PWD/db --logpath /dev/null --fork  
        scripts/test.sh 
    
    - name: Export coverage result 
      run: bash <(curl -s https://codecov.io/bash)